import { buildSubgraphSchema } from "@apollo/subgraph";
import {
  contactDefs,
  contactNoteDefs,
  tagDefs,
  milestoneTypeDefs,
  pipelineTypeDefs,
  dealTypeDefs,
  contactTagDefs,
  taskTypeDefs,
  taskDefs,
  SubTaskTypeDefs,
  platformTypeDefs,
  userSocialCredentialTypeDef,
  contactSocialIdentitiesTypeDef,
  TaskTagDefs,
  chatSessionDefs,
  chatMessageTypeDef,
  contactAttachmentDefs,
  providerMessageTypeDef,
  taskAttachmentDefs,
  contactActivityTimelineDefs,
  userDefs
} from "../typeDefs";
import {
  contactResolvers,
  contactNoteResolvers,
  dealResolvers,
  contactTagResolvers,
  tagResolvers,
  milestoneResolvers,
  pipelineResolvers,
  taskTypeResolver,
  taskResolver,
  SubTaskResolver,
  platformResolver,
  userSocialCredentialResolvers,
  contactSocialIdentitiesResolvers,
  TaskTagResolvers,
  chatSessionResolvers,
  chatMessageResolver,
  contactAttachmentResolvers,
  providerMessageResolver,
  taskAttachmentResolvers,
  contactActivityTimelineResolver,
} from "../resolvers";

export const schema = buildSubgraphSchema([
  { typeDefs: userDefs},
  { typeDefs: contactDefs, resolvers: contactResolvers },
  {
    typeDefs: contactNoteDefs,
    resolvers: contactNoteResolvers,
  },
  { typeDefs: tagDefs, resolvers: tagResolvers },
  { typeDefs: milestoneTypeDefs, resolvers: milestoneResolvers },
  { typeDefs: pipelineTypeDefs, resolvers: pipelineResolvers },
  { typeDefs: dealTypeDefs, resolvers: dealResolvers },
  { typeDefs: contactTagDefs, resolvers: contactTagResolvers },
  { typeDefs: taskTypeDefs, resolvers: taskTypeResolver },
  { typeDefs: taskDefs, resolvers: taskResolver },
  { typeDefs: SubTaskTypeDefs, resolvers: SubTaskResolver },
  { typeDefs: platformTypeDefs, resolvers: platformResolver },
  {
    typeDefs: userSocialCredentialTypeDef,
    resolvers: userSocialCredentialResolvers,
  },
  {
    typeDefs: contactSocialIdentitiesTypeDef,
    resolvers: contactSocialIdentitiesResolvers,
  },
  { typeDefs: TaskTagDefs, resolvers: TaskTagResolvers },
  { typeDefs: chatMessageTypeDef, resolvers: chatMessageResolver },
  { typeDefs: chatSessionDefs, resolvers: chatSessionResolvers },
  { typeDefs: contactAttachmentDefs, resolvers: contactAttachmentResolvers },
  { typeDefs: providerMessageTypeDef, resolvers: providerMessageResolver },
  { typeDefs: taskAttachmentDefs, resolvers: taskAttachmentResolvers},
  { typeDefs: contactActivityTimelineDefs, resolvers: contactActivityTimelineResolver},
]);
