export enum ContactActivityTypeEnum {
  CONTACT_ADDED = "CONTACT_ADDED",
  CONTACT_ASSIGNED = "CONTACT_ASSIGNED",
  TASK_CREATED = "TASK_CREATED",
  NOTE_ADDED = "NOTE_ADDED",
  PIPELINE_CREATED = "PIPELINE_CREATED",
  MAIL_SENT = "MAIL_SENT",
}
